

services:
  unityimagebuilder:
    image: unity6
    build:
      context: .
      dockerfile: ./unity6
    ports:
      - 3000:3000
    volumes:
      - /mnt/unity_data/unity_editors:/opt/unity
      - /mnt/unity_data/unity_cache:/root/.config/Unity\ Hub
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:99

  gitpull:
    image: unity6
    build:
      context: .
      dockerfile: ./unity6
    volumes:
      - /mnt/unity_data/unity_projects:/project
      - /mnt/unity_data/unity_cache:/root/.config/Unity\ Hub
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:99
    command: /bin/bash -c "cd /project && git pull"

